# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dataset_name: applovin_reporting_data
table:
  name: applovin_report
  schema:
    dimensions:
      - name: day
        type: DATE
      - name: application
        type: STRING
      - name: package_name
        type: STRING
      - name: country
        type: STRING
    metrics:
      - name: impressions
        type: INTEGER
      - name: revenue
        type: FLOAT
  partition_field: day
  clustering_fields:
    - package_name
    - country
local_dir_name: responses
local_file_name: data_from_response
